import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { NextThemeProvider } from "@/components/ThemeProvider";

const geistSans = Space_Grotesk({
  variable: "--font-space-grotesk-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className="scroll-smooth dark:bg-[#020403] bg-white"
    >
      <body suppressHydrationWarning className={`${geistSans.className}`}>
        <NextThemeProvider>{children}</NextThemeProvider>
      </body>
    </html>
  );
}
